### ISSUE TITLE
femr 0.2.0 event_stream_data_standard missing

### ISSUE THREAD

**Issue by kgweber-um** [som-shahlab/femr#187]
## Describe the bug
I'm struggling to bridge between the huggingface-friendly versions of `femr` and examples in the tutorials. When I have `femr==0.2.0` loaded, I cannot execute some basic modules.

I cannot locate the module `event_stream_data_standard`, which is proving to be a blocker in my work to resolve this. 

## Steps to reproduce the bug
```python   
os.system(f"etl_generic_omop {INPUT_DIR} {EXTRACT_DIR} {LOG_DIR} --num_threads 10")
```

## Expected results

Generation of a new `femr` database

## Actual results

```Traceback (most recent call last):
  File "/home/kate/miniconda3/envs/ehrshot/bin/etl_generic_omop", line 5, in <module>
    from femr.etl_pipelines.omop import etl_generic_omop_program
  File "/home/kate/miniconda3/envs/ehrshot/lib/python3.10/site-packages/femr/etl_pipelines/omop.py", line 11, in <module>
    from femr.datasets import EventCollection, PatientCollection, RawPatient
  File "/home/kate/miniconda3/envs/ehrshot/lib/python3.10/site-packages/femr/datasets/__init__.py", line 14, in <module>
    import event_stream_data_standard as ESDS
ModuleNotFoundError: No module named 'event_stream_data_standard'```

## Environment info

- `datasets` version: 2.15.0
- Platform: Linux-5.4.0-173-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- `huggingface_hub` version: 0.21.4
- PyArrow version: 15.0.1
- Pandas version: 2.2.1
- `fsspec` version: 2023.10.0

**Comment by EthanSteinberg** [comment]
Thanks for the message, we need to update the HF docs to point to a newer version of femr.

The problem is that event_stream_data_standard got renamed to medical event data standard: https://github.com/Medical-Event-Data-Standard

I will resolve this next week (I was super busy the last month or so as last Friday was the deadline for my dissertation).

**Comment by kgweber-um** [comment]
Awesome, thank you so much. (I was scrambling because I'm trying to finish my own dissertation :) )
