### ISSUE TITLE
Import of femr.datasets broken

### ISSUE THREAD

**Issue by jordanhilsman** [som-shahlab/femr#190]
## Describe the bug
Hi, with the release of femr v2.0, importing femr.datasets is no longer functional, the error statement is below. I recreated this in a virtual environment to ensure no dependency conflicts or other sources of the error.

## Steps to reproduce the bug. I run Python 3.10.4, I installed femr in a virtual environment.
```python
>>> import femr.datasets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jordan/.venv/lib/python3.10/site-packages/femr/datasets/__init__.py", line 201
    if event.value is None:
IndentationError: unexpected indent
```

## Environment info
- `datasets` version: 2.18.0
- Platform: Linux-6.7.3-arch1-2-x86_64-with-glibc2.39
- Python version: 3.10.4
- `huggingface_hub` version: 0.21.4
- PyArrow version: 15.0.2
- Pandas version: 2.2.1
- `fsspec` version: 2024.2.0

**Comment by jordanhilsman** [comment]
This error statement can be fixed with the indent on line 199 of the `__init__.py` file, however an error statement is then given for line 14: 
 ``` @python
>>> import femr.datasets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jordan/.local/share/pyenv/versions/3.10.4/lib/python3.10/site-packages/femr/datasets/__init__.py", line 14, in <module>
    import event_stream_data_standard as ESDS
ModuleNotFoundError: No module named 'event_stream_data_standard'
 ```
 Is this supposed to be a local input from within the package for v2.0?

**Comment by jordanhilsman** [comment]
> This error statement can be fixed with the indent on line 199 of the `__init__.py` file, however an error statement is then given for line 14:
> 
> ```
> >>> import femr.datasets
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/jordan/.local/share/pyenv/versions/3.10.4/lib/python3.10/site-packages/femr/datasets/__init__.py", line 14, in <module>
>    import event_stream_data_standard as ESDS
> ModuleNotFoundError: No module named 'event_stream_data_standard'
> ```
> 
> Is this supposed to be a local input from within the package for v2.0?

I see this was addressed in a previously closed issue from Sunday. Apologies!

**Comment by EthanSteinberg** [comment]
Sorry for the confusion! Femr 0.2.0 was sorta in rough state, as it was the bare minimum to get some code working on HF. We just released femr 0.2.3 fixes all of these issues and is now in sync with the HF repo (with a corresponding push on the HF side to bridge the gap)
